export const questions = [
    "Você se sentiu deprimido, irritável ou triste?",
    "Você sentiu fadiga ou perda de energia?",
    "Você sentiu alteração do sono (insônia, sonolência ou descontrole)?",
    "Você teve pensamentos, imagens ou memórias incontroláveis e desconfortáveis?",
    "Você sentiu medo de violência ou de ser agredido?",
    "Você sentiu desconforto em exposição pública?",
    "Você sentiu tremores internos ou em extremidades do seu corpo?",
    "Você teve pensamentos de inutilidade ou culpa?",
    "Você sentiu tontura, flutuação ou sensação de balanço?",
    "Você sentiu sua boca seca, náusea ou nó na garganta?",
    "Você sentiu perda de interesse, de sentido de vida ou do prazer?",
    "Você sentiu pressão, palpitações ou desconforto no peito?",
    "Você sentiu formigamento, sudorese, frio e/ou calor no corpo?",
    "Você sentiu medo de bichos, de lugares ou de coisas?",
    "Você sentiu que a sua visão ficou turva ou distorcida?",
    "Você sentiu dor abdominal, urgência para urinar ou defecar?",
    "Você sentiu falta de ar ou desconforto respiratório ?",
    "Você teve maus pressentimentos, preocupações, excesso de pensamentos ou apreensão?",
    "Você realizou ações, manias, impulsos e hábitos incontroláveis e/ou irresistíveis?",
    "Você sentiu desconcentração, indecisão ou dificuldade de memória?",
    "Você sentiu alteração do apetite (redução, aumento ou descontrole)?",
    "Você teve pensamentos de desesperança, morte ou suicídio?",
    "Você sentiu fraqueza ou descoordenação nas pernas?",
    "Você sentiu dores no corpo, rigidez e/ou contrações musculares?",
]

export const answers = [
    'Não apresentei estes sintomas',
    'Apresentei esses sintomas de forma leve e/ou por pouco tempo.',
    'Apresentei esses sintomas de forma moderada e/ou na metade do tempo.',
    'Apresentei esses sintomas com forte intensidade e/ou na maior parte do tempo.',
    'Apresentei esses sintomas de forma insuportável e/ou todo o tempo.',
]